2023-06-25 16:06:57,963 (41790/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-25 16:06:57,963 (41790/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-25 16:06:57,973 (41790/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/local/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "." does not exist\n'
2023-06-25 16:07:04,937 (41815/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-25 16:07:04,937 (41815/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-25 16:07:04,942 (41815/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/local/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "db" does not exist\n'
2023-06-25 16:07:16,170 (41832/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-25 16:07:16,170 (41832/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-25 16:07:16,175 (41832/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/local/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "public" does not exist\n'
2023-06-25 16:07:36,698 (41880/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-25 16:07:36,698 (41880/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-25 16:07:40,020 (41880/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"')
2023-06-25 16:07:40,023 (41880/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedObject: unrecognized configuration parameter "tables"\n'
2023-06-25 16:07:42,993 (41880/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^')
2023-06-25 16:07:42,994 (41880/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n'
